// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABMb_sYhu2MjBKag4jQ8xzOyKrUdYUMMs',
    appId: '1:289737036692:web:c3f2b1f7c20ab52305b581',
    messagingSenderId: '289737036692',
    projectId: 'auth-edb70',
    authDomain: 'auth-edb70.firebaseapp.com',
    storageBucket: 'auth-edb70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsnuHohZAaABbyd8PgqeZZEFF91Fnuw0',
    appId: '1:289737036692:android:c6cf9ef7b010586405b581',
    messagingSenderId: '289737036692',
    projectId: 'auth-edb70',
    storageBucket: 'auth-edb70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN50CpicdMKfutyC03EJkM5Nk676LffFM',
    appId: '1:289737036692:ios:85f18f5ecc99e1d405b581',
    messagingSenderId: '289737036692',
    projectId: 'auth-edb70',
    storageBucket: 'auth-edb70.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN50CpicdMKfutyC03EJkM5Nk676LffFM',
    appId: '1:289737036692:ios:de78da0c7779a47805b581',
    messagingSenderId: '289737036692',
    projectId: 'auth-edb70',
    storageBucket: 'auth-edb70.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
